### ISSUE TITLE
AddDays Function needed

### ISSUE THREAD

**Issue by C5m7b4** [C5m7b4/open-source-example#11]
Requesting an AddDays function. This function should take in either a date or a string and have the ability to add days to it. Similar to the C# Function. It could possibly return a date or a string representation of the output.

Example input is 1/1/2023 and function call looks like:
`const newDate = addDays('1/1/2023', 5)`
output is '1/6/2023'

**Comment by khushpreetsinghb** [comment]
I want to work on open-source projects. I can do this.

**Comment by C5m7b4** [comment]
Sounds good. I look forward to seeing what you contribute.

**Comment by C5m7b4** [comment]
Hey, just wondering how you were getting along or if you needed any assistance with anything. I would love to help. Just looking for good people willing to put it out there and write some cool code.

**Comment by khushpreetsinghb** [comment]
I have made the function. Here it is

function addDays(date, days) {
    var result = new Date(date);
    result.setDate(date.getDate() + days);
    result = (result.getMonth() + '/' + result.getDate() + '/' + result.getFullYear();
    return result;
}

I have also tested it. But I have never worked with JavaScript modules. So I could not understand how to implement the function.

**Comment by C5m7b4** [comment]
We could setup a meet if you like to finish implementing the changes if you think that would be beneficial.

**Comment by khushpreetsinghb** [comment]
Thank you very much. I am trying to learn modules. I think I will do it. But if I have any problems, then we will set up a meet.

**Comment by C5m7b4** [comment]
Nicely done. I'll try to post some more things for practice
